### ISSUE TITLE
Release new current version on CRAN

### ISSUE THREAD

**Issue by fmannhardt** [gertjanssenswillen/xesreadR#1]
I noted that the current CRAN version has issues exporting the example log I used in heuristicsmineR.
Steps to reproduce:

1) Install `heuristicsminerR` from here:

`remotes::install_github("fmannhardt/heuristicsmineR")`

2) Run:
```
library(bupaR)
library(heuristicsmineR)
data(L_heur_1)

write_xes(L_heur_1, "heur.xes")
```

Results in the following error:

>   |                                                                                                                                  |   0%Error in as.POSIXlt.default(x, tz = tz) : 
>   do not know how to convert 'x' to class “POSIXlt”
> In addition: Warning message:
> Unknown columns: `1` 

Using the Github version seems to fix it.

**Comment by gertjanssenswillen** [comment]
New version released
